spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    # password:

token:
  expiration_time: 86400000
  secret: "{cipher}AQBxQRVGqvqzGGTEQpErL7sUPUanVAOGl7spoUZ5OqxVZ7NSN06g+XxE05qNTUgWnVNCDTVTq4EjE+FTGmVD2Jo4lu/GqvzRWK4fVhJQxnSDoxFTpqXV+KTJ3Bv3fC6xQL/HcAu5LpDTxUXPI1Xl0n67vJyccRamysTkyPPll5Hmb/ca3k1BxMq0eSSMK3ShscUrW9PqkXjPkvsJxKmniNtIXkZ4w4M7BoqPra1c2gchLJvPZrRTgD/fDRpj2hSCD0Msh96JCrsymnF61vgQpssODMZdtfO1kM2F5xbnt9lUpa+nsYW0BwuRKXdXu+phJ/ZAsqfBQj5YEoN9bDNO2AMd/Vh1r3SxepjbSZD538W+V+4xV5hLFPtXp8MN9I4Fs24="

gateway:
  ip: 192.168.30.202

# gateway:
#   ip: 211.52.130.172

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders/
  exception:
    orders_is_empty: There is no item.
