spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQByWLcZNxUxGeLgifS8ypDVNUYaNoVAE4WsErYZzEHVwq5ONjAoiIt88oeYI3zC+BvKofSYQuy8JV+3SwpXR2lv7QDRwEmJBOwFfkDQ6inD/X6CkKzXsGPVvduu/vWT48wusY2X8MrXLxnxPHDQhX1PN87c0x2W2Pgafl6oy/f/zYIAbf49i5TecZBiU4jkiJ9UxTALdf3DqA6Tyh65RjbRNvwuw6TrYl+iI5tcGrazOTZKZeVUZa+z6vDN04+erFH5hJ0NjGZJvhKuG7OYAoqohJNUDdcik3JoAQ1wkM0UDTJKbvRfnXC8csIZD4gg7TClMSqu3/sX3o5emN4PXJSEL5jSrgFUhpjZkfac7fghsxqk5wTfsVSkZIEF2BNsxko='
    
token:
  expiration_time: 86400000
  secret: my_token_dev

gateway:
  ip: 192.168.30.202