spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    # password:

token:
  expiration_time: 86400000
  secret: sa

# gateway:
#   ip: 192.168.30.202

gateway:
  ip: 211.52.130.172

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders/
  exception:
    orders_is_empty: There is no item.
