spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}4ecf1d3fa008a040187238acf43539ef05914db55dd8c0bc76391f10747fa60b'
    
token:
  expiration_time: 86400000
  secret: my_token_dev

gateway:
  ip: 192.168.30.202